{"name": "test_add[failed]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4\n  +3\n  -4", "trace": "self = <calc_update.case.test_calc1.TestClac object at 0x00000149D4DC6898>, get_calc = <calc.calc_func.Calculator object at 0x00000149D4DC16A0>\nget_add_datas = [1, 2, 4]\n\n    @allure.story('测试加法运算')\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_add_datas):\n        '''测试加法运算'''\n        actual = get_calc.add(get_add_datas[0], get_add_datas[1])\n        if isinstance(actual, float):\n            actual = round(actual, 2)\n>       assert actual == get_add_datas[2]\nE       assert 3 == 4\nE         +3\nE         -4\n\ncase\\test_calc1.py:52: AssertionError"}, "description": "测试加法运算", "parameters": [{"name": "get_add_datas", "value": "[1, 2, 4]"}], "start": 1613224781611, "stop": 1613224781612, "uuid": "1f1375ff-f593-47f0-b959-18e80cbab660", "historyId": "712140e666ae340520cf55ed52d17416", "testCaseId": "72dca35183348fda73d20be618b8bfb0", "fullName": "case.test_calc1.TestClac#test_add", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "测试加法运算"}, {"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_calc1"}, {"name": "subSuite", "value": "TestClac"}, {"name": "host", "value": "DESKTOP-RS387SO"}, {"name": "thread", "value": "11668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_calc1"}]}